name: Latest blog posts
on:
  schedule:
    # Runs every hour
    - cron: '* 0 * * *'
  workflow_dispatch:
  
jobs:
  update-readme-with-stack-overflow:
    name: Update this repo's README with latest activity from StackOverflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          readme_path: "./profile/README.md"
          commit_message: "[BOT] Updated readme with the latest blog posts"
          feed_list: "https://blog.escape-ctf.com/feed.xml"

